name: Build xdBot

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-android64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest
          cli: latest
          target: Android64
          path: .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: xdBot-android64
          path: ${{ steps.build.outputs.build-output }}
